version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  consumer:
    build: .
    container_name: php-rabbitmq-consumer
    volumes:
      - .:/app
      - /app/vendor
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
      RABBITMQ_VHOST: /
      RABBITMQ_QUEUE_NAME: my_queue

volumes:
  rabbitmq_data: